# SPDX-FileCopyrightText: 2025 James Harton
#
# SPDX-License-Identifier: Apache-2.0

base_url = "https://beambots.dev"
title = "Beam Bots"
description = "Resilient Robotics on the BEAM - A framework for building fault-tolerant robotics applications in Elixir"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "James Harton"
github_url = "https://github.com/beam-bots/bb"
docs_url = "https://hexdocs.pm/bb"
hex_url = "https://hex.pm/packages/bb"
